sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

install:
  - luarocks --local install luafilesystem
  - luarocks --local install luacheck
  - wget -O $TRAVIS_BUILD_DIR/.luacheckrc https://ci.appveyor.com/api/projects/cuberite/cuberite/artifacts/.luacheckrc

script:
  - cd $TRAVIS_BUILD_DIR && ~/.luarocks/bin/luacheck . --codes
